services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-devops-web
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    restart: always
